import SubHubHero from '@/components/server/SubHubHero';
import FAQText from '@/components/server/FAQText';
import CTABanner from '@/components/blocks/CTABanner';
import TestimonialStrip from '@/components/blocks/TestimonialStrip';
import NavbarMorph from '@/components/client/NavbarMorph';

export const metadata = {
    title: 'Solar Heating Compatible Skirting Boards | ThermaSkirt',
    description: 'Maximise your solar thermal and PV investments. ThermaSkirt operates perfectly at low flow temperatures, allowing you to heat your home using free solar energy.',
    alternates: {
        canonical: 'https://www.discreteheat.com/homeowners/by-heat-source/solar/',
    }
};

export default function SolarPage() {
    return (
        <>
            <NavbarMorph />
            <main className="min-h-screen bg-dh-grey-light selection:bg-dh-red/20 selection:text-dh-red pt-0">
                <SubHubHero
                    badge="Solar Heating"
                    title="Harness the sun,"
                    titleHighlight="heat the floor."
                    description="Solar thermal tubes and PV-driven systems excel at producing 35-45°C warm water for free. Unfortunately, standard steel radiators are useless at these low temperatures. ThermaSkirt provides the massive surface area necessary to turn solar gains into genuine, free room heating."
                    primaryCta={{ text: "Get a System Quote", href: "/homeowners/get-a-quote" }}
                    imageSrc="/assets/images/homeowner-solar.jpg"
                    imageAlt="A modern eco-home utilizing solar panels and ThermaSkirt heating"
                />

                <section className="py-20 px-6 lg:px-12 bg-white">
                    <div className="max-w-4xl mx-auto space-y-12">
                        <article>
                            <h2 className="text-3xl font-light text-dh-dark mb-6 tracking-tight">Skirting Board Heating for Solar Systems</h2>
                            <p className="text-xl font-light text-dh-dark mb-12 leading-relaxed">
                                ThermaSkirt is an optimized low-temperature emitter perfect for solar thermal arrays and solar PV integration. By turning your entire room perimeter into a highly conductive aluminium radiator, it successfully captures and distributes the &apos;low-grade&apos; 35-45°C heat generated by the sun, displacing your reliance on grid electricity and gas.
                            </p>
                            <span className="block text-[13px] font-semibold uppercase tracking-[0.08em] text-dh-red mb-4">Low Grade Heat Utilisation</span>
                            <h3 className="text-2xl font-light text-dh-dark mb-6 tracking-tight">The Surface Area Equation</h3>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                Solar thermal evacuated tubes on your roof are fantastic at pre-heating a domestic hot water cylinder or a thermal store. On a bright spring or autumn day, they can easily push the buffer tank up to 40°C. The problem is extraction. If you pump 40°C water into a standard steel radiator, the metal barely feels lukewarm and the room stays freezing.
                            </p>
                            <p className="text-lg text-dh-grey leading-relaxed">
                                To heat a room at 40°C, you need an immense surface area to radiate the energy into the open air. Wet underfloor heating does this by using the entire floor slab. ThermaSkirt achieves this by using the entire perimeter of the room. Independent BSRIA tests confirm that by wrapping a 40°C aluminium profile around the room&apos;s edges, the system retains 48% of its output design capacity—successfully heating your home using completely free solar energy without turning your boiler on.
                            </p>
                        </article>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 my-16">
                            <div className="relative aspect-[4/3] rounded-2xl overflow-hidden bg-dh-grey-light border border-dh-grey-light/50">
                                {/* Next Image component pointing to a realistic stock/asset path */}
                                <div className="absolute inset-0 flex items-center justify-center text-dh-grey">Solar Image 1</div>
                            </div>
                            <div className="relative aspect-[4/3] rounded-2xl overflow-hidden bg-dh-grey-light border border-dh-grey-light/50">
                                <div className="absolute inset-0 flex items-center justify-center text-dh-grey">Solar Image 2</div>
                            </div>
                        </div>

                        <article>
                            <span className="block text-[13px] font-semibold uppercase tracking-[0.08em] text-dh-red mb-4">Electric Solar PV Integration</span>
                            <h3 className="text-2xl font-light text-dh-dark mb-6 tracking-tight">ThermaSkirt &apos;E&apos; and Battery Storage</h3>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                The explosive growth in domestic Solar PV panels and home battery storage (like the Tesla Powerwall) has created a new heating paradigm. Homeowners want to dump excess, free solar electricity generated during the day into heating their homes, rather than selling it back to the grid for pennies.
                            </p>
                            <p className="text-lg text-dh-grey leading-relaxed">
                                Our Electric ThermaSkirt (&apos;ThermaSkirt E&apos;) allows you to do exactly this. By hardwiring the 240V aluminium skirting boards into dedicated circuits managed by smart PV diverters (like the eddi or zappi ecosystem), you can automatically route excess solar power directly into heating your living room or home office. The aluminium profile acts as a fast-acting heat dump, turning zero-carbon sunlight into instant radiant warmth.
                            </p>
                        </article>
                    </div>
                </section>

                <TestimonialStrip
                    quote="Our solar thermal tubes were brilliant for hot water, but useless for the radiators. Changing to ThermaSkirt meant that from April to October, the 40°C water off the roof actually heats the house properly without the gas boiler ever firing up."
                    author="Ian P."
                    tags={['Eco Home', 'Solar Thermal']}
                />

                <FAQText
                    faqs={[
                        {
                            question: "Can it integrate with a thermal store accumulator?",
                            answer: "Yes. ThermaSkirt works exceptionally well when connected to the low-temperature heating loop on a buffer tank or thermal store, drawing the solar-warmed water perfectly."
                        },
                        {
                            question: "What flow temperatures are required to heat a room?",
                            answer: "Depending on your home's insulation levels (heat loss), ThermaSkirt can successfully maintain comfortable 21°C room temperatures using flow temperatures as low as 35°C, making it exceptionally compatible with solar and heat pump tech."
                        },
                        {
                            question: "Can I mix Solar PV electric heating and wet heating?",
                            answer: "Yes. Many of our clients install wet (H2O) ThermaSkirt on the ground floor driven by a heat pump, and install Electric (E) ThermaSkirt upstairs wired to a PV diverter switch to 'soak up' excess daytime solar generation."
                        }
                    ]}
                />

                <CTABanner
                    heading="Zero carbon heating. Zero wall clutter."
                    description="Upload your eco-build plans for a fast, free itemised quote."
                    primaryCTA="Get a Free Quote"
                    primaryCTALink="/homeowners/get-a-quote"
                    secondaryCTA="Find an Installer"
                    secondaryCTALink="/homeowners/find-an-installer"
                />
            </main>
        </>
    );
}
