import SubHubHero from '@/components/server/SubHubHero';
import StatsStrip from '@/components/blocks/StatsStrip';
import FAQText from '@/components/server/FAQText';
import CTABanner from '@/components/blocks/CTABanner';
import TestimonialStrip from '@/components/blocks/TestimonialStrip';
import ExploreCategorySection from '@/components/blocks/ExploreCategorySection';
import NavbarMorph from '@/components/client/NavbarMorph';
import Link from 'next/link';

export const metadata = {
    title: 'Solar Heating Compatible Skirting Boards | ThermaSkirt',
    description: 'Maximise your solar thermal and PV investment. ThermaSkirt operates at 35–45°C flow temperatures, turning free solar energy into real room heating. Pairs with battery storage for sub-gas running costs.',
    alternates: {
        canonical: 'https://www.discreteheat.com/homeowners/by-heat-source/solar/',
    },
    openGraph: {
        images: [{ url: 'https://www.discreteheat.com/MediaHandler.ashx?id=b6b35020-a668-4a2a-8072-c8f957bc442b', width: 1200, height: 630, alt: 'Solar Heating Compatible Skirting Boards | ThermaSkirt' }],
    },
};

export default function SolarPage() {
    return (
        <>
            <NavbarMorph />
            <main className="min-h-screen bg-dh-grey-light selection:bg-dh-red/20 selection:text-dh-red pt-0">
                <SubHubHero
                    badge="Solar Heating"
                    title="Harness the sun,"
                    titleHighlight="heat the home."
                    description="Solar thermal tubes and PV-driven systems produce 35–45°C warm water for free. Standard steel radiators are nearly useless at these temperatures. ThermaSkirt provides the massive surface area needed to turn solar gains into genuine, free room heating—independently verified by BSRIA."
                    primaryCta={{ text: "Get a System Quote", href: "/homeowners/get-a-quote" }}
                    secondaryCta={{ text: "See ThermaSkirt-e for PV", href: "/homeowners/by-heat-source/electric" }}
                    imageSrc="https://www.discreteheat.com/MediaHandler.ashx?id=b6b35020-a668-4a2a-8072-c8f957bc442b"
                    imageAlt="A modern eco-home with rooftop solar panels and ThermaSkirt skirting board heating inside"
                />

                <StatsStrip
                    stats={[
                        { value: '48%', label: 'Output Retained at 40°C', source: 'BSRIA tested, vs 30% for radiators' },
                        { value: '0p/kWh', label: 'Solar Self-Consumption', source: 'free heat from your own panels' },
                        { value: '5.6p/kWh', label: 'Off-Peak Battery Cost', source: 'cheaper than gas with storage' },
                        { value: '35°C', label: 'Minimum Flow Temp', source: 'captures lowest-grade solar heat' },
                    ]}
                />

                {/* ── Section 1: Solar Thermal ── */}
                <section className="py-20 px-6 lg:px-12 bg-white">
                    <div className="max-w-4xl mx-auto space-y-12">
                        <article>
                            <h2 className="text-3xl font-light text-dh-dark mb-6 tracking-tight">Skirting Board Heating for Solar Systems</h2>
                            <p className="text-xl font-light text-dh-dark mb-12 leading-relaxed">
                                ThermaSkirt is an optimised low-temperature emitter for solar thermal arrays and solar PV integration. By turning your entire room perimeter into a highly conductive aluminium radiating surface, it captures and distributes the low-grade 35–45°C heat generated by the sun—displacing your reliance on grid electricity and gas. BSRIA testing confirms 48% output retention at 40°C flow temperatures, compared to approximately 30% for conventional panel radiators.
                            </p>

                            <span className="block text-[13px] font-semibold uppercase tracking-[0.08em] text-dh-red mb-4">Solar Thermal</span>
                            <h3 className="text-2xl font-light text-dh-dark mb-6 tracking-tight">The Surface Area Equation</h3>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                Solar thermal evacuated tubes on your roof are excellent at pre-heating a domestic hot water cylinder or thermal store. On a bright spring or autumn day, they can push the buffer tank up to 40°C. The problem is extraction: if you pump 40°C water into a standard steel radiator, the metal barely feels lukewarm and the room stays cold. The temperature difference between the emitter and the room (the &ldquo;delta T&rdquo;) is simply too small for a small radiator surface to emit meaningful heat.
                            </p>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                To heat a room at 40°C flow, you need an immense surface area. Wet underfloor heating achieves this by using the entire floor slab. ThermaSkirt achieves it by using the entire perimeter of the room. A typical living room has 12–15 linear metres of skirting—that&apos;s 12–15 metres of continuous aluminium radiating surface, capturing every available watt from your solar thermal buffer.
                            </p>
                            <p className="text-lg text-dh-grey leading-relaxed">
                                Independent <Link href="/specifiers/technical-data/bsria-test-results" className="text-dh-red hover:underline">BSRIA tests</Link> confirm that at 40°C flow, ThermaSkirt BM2 delivers 44W per linear metre—enough to heat a well-insulated room entirely from solar energy without firing your boiler at all during the shoulder months (March–May, September–November).
                            </p>
                        </article>

                        {/* ── Section 2: Solar PV + Electric ── */}
                        <article>
                            <span className="block text-[13px] font-semibold uppercase tracking-[0.08em] text-dh-red mb-4">Solar PV Integration</span>
                            <h3 className="text-2xl font-light text-dh-dark mb-6 tracking-tight">ThermaSkirt-e and Battery Storage</h3>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                The growth in domestic solar PV and home battery storage has created a new heating paradigm. Homeowners want to dump excess, free solar electricity into heating their homes rather than exporting it to the grid for 4–5p/kWh.
                            </p>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                <Link href="/homeowners/by-heat-source/electric" className="text-dh-red hover:underline">ThermaSkirt-e</Link> (our 240V electric version) allows you to do exactly this. By hardwiring the aluminium skirting boards into dedicated circuits managed by a smart PV diverter (like the myenergi eddi), you can automatically route excess solar power directly into heating your living room or home office. The aluminium profile acts as a fast-acting heat dump, turning zero-carbon sunlight into instant radiant warmth at zero marginal cost.
                            </p>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
                                <div className="p-8 bg-dh-grey-light rounded-[14px]">
                                    <h4 className="text-lg font-semibold text-dh-dark mb-3">Daytime Solar Diversion</h4>
                                    <p className="text-sm text-dh-grey leading-relaxed">
                                        A smart PV diverter detects when your solar panels are generating more electricity than your home is consuming. It automatically routes the surplus into ThermaSkirt-e—heating your rooms for free instead of exporting to the grid at 4–5p/kWh.
                                    </p>
                                </div>
                                <div className="p-8 bg-dh-grey-light rounded-[14px]">
                                    <h4 className="text-lg font-semibold text-dh-dark mb-3">Battery + Off-Peak Strategy</h4>
                                    <p className="text-sm text-dh-grey leading-relaxed">
                                        A 15kWh home battery (Tesla Powerwall, GivEnergy) charges overnight at 5.6p/kWh on an off-peak tariff, then discharges through ThermaSkirt-e during the day. Effective heating cost: below 13.6p/kWh—cheaper than gas at current rates. Pair this with daytime solar top-up for even greater savings.
                                    </p>
                                </div>
                            </div>
                        </article>

                        {/* ── Section 3: Mixed Systems ── */}
                        <article>
                            <span className="block text-[13px] font-semibold uppercase tracking-[0.08em] text-dh-red mb-4">Hybrid Configurations</span>
                            <h3 className="text-2xl font-light text-dh-dark mb-6 tracking-tight">Mix Wet and Electric for Maximum Efficiency</h3>
                            <p className="text-lg text-dh-grey leading-relaxed mb-6">
                                Many solar homeowners achieve the best economics by combining both ThermaSkirt products. A typical setup: ThermaSkirt H2O on the ground floor connected to a heat pump or gas boiler via the solar thermal buffer, and ThermaSkirt-e upstairs wired to a PV diverter to soak up excess daytime solar generation.
                            </p>
                            <p className="text-lg text-dh-grey leading-relaxed">
                                This hybrid approach means the ground floor benefits from the heat pump&apos;s high COP for bulk heating, while the upstairs bedrooms are heated entirely by free solar electricity during the day—prewarmed and comfortable by the time the family heads upstairs in the evening. The systems operate independently, so there&apos;s no complex integration or shared controls.
                            </p>
                        </article>

                        {/* ── Section 4: Economics Summary ── */}
                        <article>
                            <span className="block text-[13px] font-semibold uppercase tracking-[0.08em] text-dh-red mb-4">Economics</span>
                            <h3 className="text-2xl font-light text-dh-dark mb-6 tracking-tight">What Does Solar-Powered Heating Actually Cost?</h3>
                            <p className="text-lg text-dh-grey leading-relaxed mb-8">
                                The running cost depends entirely on how you source the electricity. Here&apos;s a comparison using current UK energy prices.
                            </p>

                            <div className="overflow-x-auto mb-8">
                                <table className="w-full text-left border-collapse">
                                    <thead>
                                        <tr className="border-b-2 border-dh-dark">
                                            <th className="py-3 pr-6 text-sm font-semibold text-dh-dark uppercase tracking-wider">Source</th>
                                            <th className="py-3 pr-6 text-sm font-semibold text-dh-dark uppercase tracking-wider">Cost per kWh</th>
                                            <th className="py-3 text-sm font-semibold text-dh-dark uppercase tracking-wider">Notes</th>
                                        </tr>
                                    </thead>
                                    <tbody className="text-dh-grey">
                                        <tr className="border-b border-dh-grey-light">
                                            <td className="py-3 pr-6 font-medium">Solar PV (self-consumed)</td>
                                            <td className="py-3 pr-6 text-dh-red font-semibold">0p</td>
                                            <td className="py-3">Free electricity diverted from export</td>
                                        </tr>
                                        <tr className="border-b border-dh-grey-light">
                                            <td className="py-3 pr-6 font-medium">Battery (off-peak charged)</td>
                                            <td className="py-3 pr-6">5.6–7p</td>
                                            <td className="py-3">Octopus Intelligent Go / Economy 7</td>
                                        </tr>
                                        <tr className="border-b border-dh-grey-light">
                                            <td className="py-3 pr-6 font-medium">Gas boiler (condensing)</td>
                                            <td className="py-3 pr-6">~7p</td>
                                            <td className="py-3">Assuming 90% boiler efficiency</td>
                                        </tr>
                                        <tr className="border-b border-dh-grey-light">
                                            <td className="py-3 pr-6 font-medium">Heat pump (COP 3.5)</td>
                                            <td className="py-3 pr-6">~7p</td>
                                            <td className="py-3">Standard electricity tariff</td>
                                        </tr>
                                        <tr className="border-b border-dh-grey-light">
                                            <td className="py-3 pr-6 font-medium">Standard electricity (flat rate)</td>
                                            <td className="py-3 pr-6">24p</td>
                                            <td className="py-3">Only for supplementary rooms</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <p className="text-sm text-dh-grey">
                                Prices based on typical UK tariffs as of 2025. Actual costs depend on your tariff, solar array size, battery capacity, and consumption patterns.
                            </p>
                        </article>
                    </div>
                </section>

                <TestimonialStrip
                    quote="Our solar thermal tubes were brilliant for hot water, but useless for the radiators. Switching to ThermaSkirt meant that from April to October, the 40°C water off the roof actually heats the house properly without the gas boiler ever firing up."
                    author="Ian P."
                    tags={['Eco Home', 'Solar Thermal']}
                />

                <FAQText
                    heading="Solar Heating — Common Questions"
                    faqs={[
                        {
                            question: "Can ThermaSkirt integrate with a thermal store or accumulator?",
                            answer: "Yes. ThermaSkirt H2O works exceptionally well connected to the low-temperature heating loop on a buffer tank or thermal store, drawing solar-warmed water at 35–45°C and distributing it effectively around the room perimeter."
                        },
                        {
                            question: "What flow temperatures are needed to heat a room?",
                            answer: "Depending on your home's insulation (heat loss), ThermaSkirt can maintain a comfortable 21°C room temperature using flow temperatures as low as 35°C. At 40°C, the BM2 profile delivers 44W per linear metre—enough for most well-insulated rooms using solar thermal alone."
                        },
                        {
                            question: "Can I mix Solar PV electric heating and wet heating?",
                            answer: (<>Yes. Many homeowners install ThermaSkirt H2O on the ground floor driven by a heat pump or boiler via the solar buffer, and <Link href="/homeowners/by-heat-source/electric" className="text-dh-red hover:underline">ThermaSkirt-e</Link> upstairs wired to a PV diverter to soak up excess daytime solar generation. The systems operate independently.</>)
                        },
                        {
                            question: "Which PV diverter works with ThermaSkirt-e?",
                            answer: "Any smart PV diverter that can switch a 240V load will work. The myenergi eddi is the most popular choice among ThermaSkirt-e customers, but any comparable device (iBoost, Solar iBoost+) will function identically."
                        },
                        {
                            question: "Is solar thermal heating practical in the UK?",
                            answer: "In the shoulder months (March–May, September–November), solar thermal evacuated tubes routinely produce 35–45°C buffer tank temperatures on bright days. Combined with ThermaSkirt's low-temperature efficiency, this is enough to heat well-insulated rooms without firing the boiler. In deep winter (December–February), you'll still need a boiler or heat pump as backup."
                        },
                        {
                            question: "How does battery storage change the economics?",
                            answer: "A 15kWh home battery charging overnight at 5.6p/kWh and discharging through ThermaSkirt-e during the day delivers an effective heating cost below 13.6p/kWh—cheaper than gas. If you also top up the battery from solar PV during daylight hours, the average cost drops further."
                        },
                    ]}
                />

                <ExploreCategorySection
                    heading="Explore more heating options"
                    description="See how ThermaSkirt works with other heating systems and project types."
                    tiles={[
                        { title: 'Heat Pump', description: 'Optimised for 35–45°C flow temperatures. Improves COP by up to 0.5.', href: '/homeowners/by-heat-source/heat-pump' },
                        { title: 'Electric Only', description: 'ThermaSkirt-e: 240V heating with zero plumbing.', href: '/homeowners/by-heat-source/electric' },
                        { title: 'Gas or Oil Boiler', description: 'Direct replacement for radiators on any existing wet system.', href: '/homeowners/by-heat-source/boiler' },
                        { title: 'New Build Projects', description: 'Designed in from the start for maximum efficiency.', href: '/homeowners/by-project/new-build' },
                        { title: 'Garden Room Projects', description: 'Purpose-built heating for detached garden buildings.', href: '/homeowners/by-room/garden-room' },
                        { title: 'ThermaSkirt vs Underfloor Heating', description: 'Why skirting board heating beats UFH in retrofits.', href: '/homeowners/vs/underfloor-heating' },
                        { title: 'Cost Guide', description: 'Transparent pricing for every ThermaSkirt configuration.', href: '/homeowners/cost-guide' },
                    ]}
                />

                <CTABanner
                    heading="Zero carbon heating. Zero wall clutter."
                    description="Upload your eco-build plans for a fast, free itemised quote. We'll calculate the exact ThermaSkirt configuration for your solar setup."
                    primaryCTA="Get a Free Quote"
                    primaryCTALink="/homeowners/get-a-quote"
                    secondaryCTA="Find a ThermaSkirt Installer"
                    secondaryCTALink="/homeowners/find-an-installer"
                    additionalLinks={[
                        { text: "View Cost Guide", href: "/homeowners/cost-guide" },
                        { text: "Compare ThermaSkirt vs Underfloor Heating", href: "/homeowners/vs/underfloor-heating" },
                    ]}
                />
            </main>
        </>
    );
}
